version: '3.8'
services:
  app:
    image: violet:1.0.3
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "4000:3000"