-- AlterTable
ALTER TABLE `Ticket` ADD COLUMN `label` ENUM('DOCUMENTATION', 'BUG', 'FEATURE') NOT NULL DEFAULT 'DOCUMENTATION',
    ADD COLUMN `priority` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'LOW';
